# Generated by Django 4.0.4 on 2022-05-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contents',
            new_name='content',
        ),
    ]
